BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            text: '34'
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.2
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert m to km'
    Label:
        text: 'blah'
        color: (1, 1, 0, 1)
